#ifndef SFT_SFT_CONSTANTS_HPP
#define SFT_SFT_CONSTANTS_HPP

#define MAX_PACKET_SIZE 8192
#define BACKLOG 1
#define PACKET_HEADER_SIZE 4
#define PACKET_TERMINATION_HEADER 0xFFFFFFFF
#define READ_RECEIPT "OK"
#define READ_RECEIPT_SIZE 2

#endif //SFT_SFT_CONSTANTS_HPP
